sudo: required
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - xvfb
language: node_js
node_js:
- '10.12.0'
before_install:
- export NG_CLI_ANALYTICS=false
- export DISPLAY=:99.0
before_script:
# more heap mem per https://github.com/angular/angular-cli/issues/12645, https://github.com/npm/npm/issues/12238#issuecomment-367147962
- export NODE_OPTIONS="--max_old_space_size=4096"
- npm install -g gulp
- npm install -g istanbul-combine
script:
- npm run lint:lib
- ng build igniteui-angular --prod
- npm run build:style
# - if [ -z "${TRAVIS_TAG}" ]; then npm run test:lib:perf; fi
- if [ -z "${TRAVIS_TAG}" ]; then npm run test:lib:others; fi
- if [ -z "${TRAVIS_TAG}" ]; then npm run test:lib:grid; fi
- if [ -z "${TRAVIS_TAG}" ]; then npm run test:lib:tgrid; fi
- if [ -z "${TRAVIS_TAG}" ]; then npm run test:lib:hgrid; fi
- if [ -z "${TRAVIS_TAG}" ]; then istanbul-combine -d coverage -p none -r lcov -r html coverage/hierarchical-grid/coverage-final.json coverage/tree-grid/coverage-final.json coverage/non-grid/coverage-final.json coverage/grid/coverage-final.json; fi
- if [ -z "${TRAVIS_TAG}" ]; then npm run test:schematics; fi
- if [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_REPO_SLUG}" == "IgniteUI/igniteui-angular" ]; then cat ./coverage/lcov.info | coveralls; fi

before_deploy:
- npm run build:schematics
- npm run build:migration
# move to dist
- cd dist/igniteui-angular
# update package versions
- npm version "${TRAVIS_TAG}" --no-git-tag-version --save
- if [[ "${TRAVIS_TAG}" == *"beta"* || "${TRAVIS_TAG}" == *"rc"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

# copy readme
- cp ../../README.md README.md

deploy:
  provider: npm
  tag: "${NPM_TAG}"
  skip_cleanup: true
  email: igniteui@infragistics.com
  api_key:
    secure: DzxT8e3ryMBPMgx+6toU7+O+1nBLzjCAO4vyDQbze9Fi1jJ23PUUXuG9UmXqnzPUJ64uK4qzi40QiPdk4P0AsOiBr66fQtn02f/Yo1F42r13X9jKuqOdJlRl3dTWPGt5HOBO4YUq6BYA1HAh09/nsgLt670Wk2I8PMNpUiuTFI1F6vhGFsrjEaKbknrZhrQzfAxbTkbZe3RJmrEJQzU5CfFkZzoqsqpS20tFSSNiiPVy6G5OmAMW5f26klq5T0BZ0xBAf2AlXEmGo+LS+65Mbe+yQb1v/IUPk+YY4gwzQQEEh9d+MNU+tMOIVfkqyj5MIdILEIoLMlHKTtaqh8GsxOr2sFw6a4tTKpTqr4yBwuGspa/KjexC/41QVHQjaG0wAekuZluUOL+5I2jYzmVPAFSeiXhor4DFcp+Eh7uwEMaw1paX5DW8UiI8r2FU8RcHE75MN/EOSLE1+9He+RfxnHZW3MyOhOnvZt08+/WoFR6l1OpMM8mVVfHFFVvSk/QVbjFobbvzl5ecNMCS2H8EAJx8mYhwMgTxgf9Sw2AHKh0mgOlRBC9Ox17Hk2VKMcL7sgGY+7btP5mgqW1P/HHxXSAWaqS2e01L+GK5EG618R3Gz+Fphr6ZIyNqQ6BCc1UpJQZFJVVsPAJMMBg7Or5vcYJlxYPXOM5jLm8lzo9hSxA=
  on:
    tags: true
    repo: IgniteUI/igniteui-angular
