pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: npm ci
  displayName: 'Install dependencies'
  env:
    AZURE_PIPELINES: "true"

- script: sudo npm install -g istanbul-combine
  displayName: 'Install coverage combiner'
  env:
    AZURE_PIPELINES: "true"

- script: npm run lint:lib
  displayName: 'Run lint'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run build:lib
  displayName: 'Build source code and styles'

- script: npm run test:lib:azure:others
  displayName: 'Run non-grid tests'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run test:lib:azure:grid
  displayName: 'Run grid tests'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run test:lib:azure:tgrid
  displayName: 'Run tree grid tests'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run test:lib:azure:hgrid
  displayName: 'Run hierarchical grid tests'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run test:styles
  displayName: 'Run styling library tests'

## Use only Github actions for publishing coveralls.io status
# - script: istanbul-combine -d coverage -p none -r lcov -r cobertura coverage/hierarchical-grid/coverage-final.json coverage/tree-grid/coverage-final.json coverage/non-grid/coverage-final.json coverage/grid/coverage-final.json
#   displayName: 'Combine coverage results'
#   env:
#     AZURE_PIPELINES: "true"

# - script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#   condition: and(succeeded(), eq(variables['system.teamProject'], 'igniteui-angular'))
#   displayName: 'Code coverage @ Coveralls'
#   env:
#     COVERALLS_REPO_TOKEN: $(coveralls.repoToken)

- script: npm run test:schematics
  displayName: 'Run migrations & schematics'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
