pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'
  env:
    AZURE_PIPELINES: "true"

- script: npm run lint:lib
  displayName: 'Run lint'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run build:lib
  displayName: 'Build source code and styles'

- script: npm run build:typedoc:en:production
  displayName: 'Build typedoc EN'

- script: npm run build:sassdoc:en:production
  displayName: 'Build sassdoc EN'

- script: npm run test:lib:azure
  displayName: 'Run all tests'
  env:
    NODE_OPTIONS: "--max_old_space_size=4096"

- script: npm run test:styles
  displayName: 'Run styling library tests'

## Use only Github actions for publishing coveralls.io status
# - script: istanbul-combine -d coverage -p none -r lcov -r cobertura coverage/hierarchical-grid/coverage-final.json coverage/tree-grid/coverage-final.json coverage/non-grid/coverage-final.json coverage/grid/coverage-final.json
#   displayName: 'Combine coverage results'
#   env:
#     AZURE_PIPELINES: "true"

# - script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#   condition: and(succeeded(), eq(variables['system.teamProject'], 'igniteui-angular'))
#   displayName: 'Code coverage @ Coveralls'
#   env:
#     COVERALLS_REPO_TOKEN: $(coveralls.repoToken)

- script: npm run test:schematics
  displayName: 'Run migrations & schematics'

- script: npm run test:i18n
  displayName: 'Test i18n'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: Cobertura
#     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
#     reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
